#!/usr/bin/env node

'use strict';

let http = require('http')
let url = require('url')
let util = require('util')
let fs = require('fs')
let cp = require('child_process')
let os = require('os')

let multiparty = require('multiparty')

// a flag to prevent a double erroring during a request
let request_had_error = false

let log =  console.error.bind(console, 'imgur-server-stub:')

let errx = function(res, code, msg) {
    if (!request_had_error) {
	res.setHeader('Access-Control-Allow-Origin', '*')
	res.statusCode = code
	res.statusMessage = msg
	res.end()
    }
    log(msg instanceof Error ? msg : `ERROR: ${msg}`)
    request_had_error = true
}

let listen = function(srv) {
    srv.listen(process.env.PORT || 3000,
	       function() {
		   log('Listening: http://' +
		       this.address().address +
		       (this.address().port === 80 ?
			"" : ":" + this.address().port))
	       })
}


// Main

let tmpdir = __dirname + '/.tmp'
let server = http.createServer(function(req, res) {
    request_had_error = false
    res.setHeader('Access-Control-Allow-Origin', '*')

    // preflighted requests
    if (req.method === "OPTIONS") {
	res.statusCode = 200
	res.setHeader('Access-Control-Allow-Headers', 'Authorization')
	res.end()
	return
    }

    if (req.method === "GET") {
	res.writeHead(200, {'Content-Type': 'image/jpeg'})
	let stream = fs.createReadStream(__dirname + '/data/rowan-atkinson-parrot.jpg')
	stream.pipe(res);
	return
    }

    if (req.method !== "POST") {
	errx(res, 501, "not implemented")
	return
    }

    let purl = url.parse(req.url, true)
    if (purl.path !== '/3/image.json') {
	errx(res, 404, "not found")
	return
    }

    // process uploads
    try { fs.mkdirSync(tmpdir) } catch (e) { /* empty */ }
    let form = new multiparty.Form({'uploadDir': tmpdir})
    form.parse(req, (err, fields, files) => {
	if (err) {
	    errx(res, 500, err)
	    return
	}

	if (!req.headers.authorization
	    || !req.headers.authorization.match(/^client-id [a-zA-Z0-9]+/i)) {
	    errx(res, 401, 'Unauthorized')
	    return
	}
	if (!files.image) {
	    errx(res, 400, 'image key is requred')
	    return
	}

	if (files.image[0].headers['content-type'] !== "image/jpeg") {
	    errx(res, 500, 'Could not process upload!')
	    return
	}

	res.setHeader('Content-Type', 'application/json')
	res.statusCode = 200
	res.end(JSON.stringify({
	    data: {
		"_multiparty": {fields, files},

		// curl -v -H 'Authorization: Client-ID dc708f3823b7756' -F image=@file.jpg https://api.imgur.com/3/image.json
		"id": "who cares",
		"title": null,
		"description": null,
		"datetime": 1484068035,
		"type": "image/jpeg",
		"animated": false,
		"width": 480,
		"height": 360,
		"size": files.image[0].size,
		"views": 0,
		"bandwidth": 0,
		"vote": null,
		"favorite": false,
		"nsfw": null,
		"section": null,
		"account_url": null,
		"account_id": 0,
		"is_ad": false,
		"in_gallery": false,
		"deletehash": "YTxyUTBAwGCixGL",
		"name": "",
		"link": 'http://localhost' + files.image[0].path.replace(os.homedir(), `/~${os.userInfo().username}`)
	    },
	    success : true,
	    status: 200
	}, null, 2))
    })
})

server.on('error', function(err) {
    log(err)
})

server.on('clientError', function(err, socket) {
    socket.write('HTTP/1.1 400 Bad Request\r\n')
    socket.write('Content-Length: 0\r\n')
    socket.write('Access-Control-Allow-Origin: *\r\n')
    socket.end('\r\n')
})

// remove the tmp upload dir
process.on('SIGINT', () => {
    let cmd = `rm -rf ${tmpdir}`
    console.error(cmd)
    cp.execSync(cmd)
    process.exit(1)
})

listen(server)
